@startuml
title Діаграма активностей роботи застосунку оптимізації

start

:Запустити програму;
:Показати головне вікно\nта панель налаштування;

:Користувач обирає цільову функцію,\nметод, спосіб пошуку кроку,\nвводить стартову точку та параметри;
:Натиснути кнопку "Запустити";

:Перевірити коректність\nвведених даних;

if (Дані коректні?) then (так)
  if (Обрано режим\n"Запустити всі методи"?) then (так)
    :Послідовно створювати та\nзапускати всі доступні методи;
    :Для кожного методу\nзбирати результати обчислень;
    :Сформувати зведену таблицю\nіз порівнянням методів;
    :Показати діалог зі зведеною таблицею\nта короткою рекомендацією;
    :За потреби побудувати траєкторію\nдля одного з методів;
  else (ні)
    :Створити вибраний метод\nоптимізації;
    repeat
      :Виконати чергову ітерацію\nобчислень;
      :Оновити таблицю ітерацій\n(додати новий рядок);
      :Оновити графіки\n(f(k), контур, траєкторія, 3D);
    repeat while (Критерій зупинки\nще не виконано?) is (так)
    :Зберегти підсумкову точку,\nзначення функції та статистику;
    :Оновити блок статистики\nпід таблицею;
  endif
  :Показати повідомлення\nпро успішне завершення обчислень;
else (ні)
  :Показати повідомлення\nпро помилку у вхідних даних;
  :Залишити користувача\nна екрані налаштування задачі;
endif

stop
@enduml
